# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: APC Elettro Rappresentanze
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "https://dleone81.github.io/apcelettro/" # the subpath of your site, e.g. /blog
url: "https://www.apcelettrorappresentanze.it" # the base hostname & protocol for your site, e.g. http://example.com
company_name: APC Elettrorappresentanze srl
company_addr: >- 
  Via Fratello Bandiera 2<br>
  Treviolo 24048 BG<br>
company_phone: (+39) 351 8473235
company_id: 04410090163
company_share_capital: 10000 euro (i.v.)
company_email: info@apcelettrorappresentanze.it
company_pec_email: apcelettrorappresentanzesrl@pec.it

linkedin_page: "https://www.linkedin.com/company/apcelettro"
facebook_page: "https://www.facebook.com/apcelettrorappresentanze/"
instagram_page: "https://www.instagram.com/apc_elettro/"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

jekyll_admin:
  hidden_links:
    - staticfiles
    - datafiles
    - configuration

collections:
  authors:
    output: true

defaults:
- scope:
    path: ""
    type: "posts"
  values:
    layout: "blog"
    title: ""
    subtitle: ""
    description: ""
    tag: ""
    author: ""